version: '3.5'

services:
  rabbitmq:
    image: rabbitmq
    hostname: rabbitmq
    container_name: rabbitmq
    volumes:
      - C:\rabbitmq\db:c:/RabbitMQ-data/db
      - C:\rabbitmq\log:c:/RabbitMQ-data/log
    ports:
      - "15672:15672"
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: nat
