version: '3.5'

services:
  api:
    image: demo-api
    build:
      context: .
      dockerfile: Demo.Web\Dockerfile
    container_name: demo-api
    environment:
      - Services__RabbitMQ=rabbitmq
      - Database__ConnectionString=Server=mssql;Database=demodb;User Id=sa;Password=nRhtG1c9;
    ports:
      - "80"
    restart: on-failure
  worker:
    image: demo-worker
    build:
      context: .
      dockerfile: Demo.Worker\Dockerfile
    container_name: demo-worker
    environment:
      - Services__RabbitMQ=rabbitmq
      - Database__ConnectionString=Server=mssql;Database=demodb;User Id=sa;Password=nRhtG1c9;
    restart: on-failure
