version: '3.5'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  worker:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
networks:
  default:
    external:
      name: nat
